# AEC Directory Scanner Configuration File
# This file contains all available configuration options with default values
# Uncomment and modify values as needed

# Database Configuration
database:
  type: "sqlite"  # or "postgresql"
  path: "aec_scanner.db"  # For SQLite
  # PostgreSQL settings (uncomment if using PostgreSQL)
  # host: "localhost"
  # port: 5432
  # database: "aec_projects"
  # username: "aec_user"
  # password: "secure_password"

# File Scanning Configuration
scanning:
  max_workers: 4  # Number of parallel processing threads
  batch_size: 1000  # Files to process in each batch
  max_file_size_mb: 500  # Maximum file size to process (MB)
  generate_hashes: false  # Whether to generate file hashes (resource intensive)
  excluded_extensions:
    - ".tmp"
    - ".log"
    - ".bak"
    - ".swp"
  excluded_directories:
    - "temp"
    - ".git"
    - "__pycache__"
    - "node_modules"

# Metadata Extraction Configuration
metadata_extraction:
  pdf_processing:
    ocr_enabled: false  # Optical Character Recognition (requires tesseract)
    ocr_language: "eng"
    extract_images: false
  
  cad_processing:
    extract_layers: true
    extract_blocks: true
    max_entities: 10000  # Maximum CAD entities to process
  
  office_documents:
    extract_embedded_objects: false
    process_formulas: true

# File Naming Convention Patterns
file_naming:
  project_number_regex: "PROJ\\d+"
  drawing_number_regex: "[A-Z]-\\d{3}"
  revision_regex: "R\\d+"
  discipline_codes:
    A: "Architectural"
    M: "Mechanical"
    S: "Structural"
    E: "Electrical"
    R: "Civil"

# Logging Configuration
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  file_path: "logs/scanner.log"
  max_file_size_mb: 10
  backup_count: 5
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# Reporting Configuration
reporting:
  auto_generate: true
  output_formats:
    - "html"
    - "json"
  include_thumbnails: false
  max_report_size_mb: 50

# Performance Configuration
performance:
  connection_timeout: 30  # Database connection timeout (seconds)
  query_timeout: 60  # Database query timeout (seconds)
  cache_size_mb: 100  # Memory cache size limit
  enable_compression: true  # Compress stored metadata